I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script
    with Dissolve(0.5)
IOError: Couldn't find file 'scene1.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script
    with Dissolve(0.5)
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/ast.py", line 1443, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/exports.py", line 1684, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/display/core.py", line 2762, in do_with
    clear=clear)
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/display/core.py", line 4025, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/audio/audio.py", line 1162, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/audio/audio.py", line 1140, in periodic_thread_main
    periodic_pass()
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/audio/audio.py", line 1082, in periodic_pass
    c.periodic()
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/audio/audio.py", line 518, in periodic
    topf = load(filename)
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "C:\Users\ferrer\Documents\Courses\2021_2S\CSCI 270\renpy-7.4.11-sdk/renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'scene1.mp3'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Help Visitor 1.0
Wed Mar 30 08:28:47 2022
